language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls


services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE politestdb;" -U postgres
  - psql -c "CREATE USER tico WITH PASSWORD 'password';" -U postgres

env:
  - SECRET_KEY="b'\xd1\x01\\\xda\xb4\x93\x7f\x82\xd2-\xbbF\xba\xb3\xfc\x9c\xe0\xdb\x8c9$\x992\x1d'" DATABASE_NAME="politestdb" DATABASE_USER="tico" DATABASE_PASS="password" DATABASE_HOST="127.0.0.1" DATABASE_PORT="5432" DATABASE_TEST_NAME="politestdb"
  
  
# command to run tests
script:
  - pytest --cov=app

  
after_success:
  - coveralls


